info:
  welcome: –ü—Ä–∏–≤–µ—Ç! –°–µ–π—á–∞—Å —Ç—ã –∏—Å–ø–æ–ª—å–∑—É–µ—à—å –º–æ–¥–µ–ª—å
  txt_prompt: prompt
  img_photo: photo
  img_prompt: prompt
  rescale_photo: photo
  select_model: –í—ã–±–µ—Ä–∏ —Å–≤–æ–µ–≥–æ <b>—Ö—É–¥–æ–∂–Ω–∏–∫–∞</b>
  select_orientation_mode: Select orient mode
  canceled: ‚úÖ Canceled
  in_progress: –†–∏—Å—É—é –∫–∞—Ä—Ç–∏–Ω–∫–∏ üé® ...
  in_progress_text: –†–∏—Å—É—é –∫–∞—Ä—Ç–∏–Ω–∫–∏ üé® ...
  in_progress_img: –ò—Å–ø—Ä–∞–≤–ª—è—é —Ç–≤–æ–∏ –∫–∞—Ä—è–∫—É–ª–∏ üé® ...
  in_progress_rescale: –£–ª—É—á—à–∞—é –∫–∞—á–µ—Å—Ç–≤–æ üñº ...

  scores:
    creativity: –ö—Ä–µ–∞—Ç–∏–≤–Ω–æ—Å—Ç—å
    skill: –ù–∞–≤—ã–∫

help:
  txt2img: ‚úèÔ∏è  –ß—Ç–æ–±—ã –Ω–∞—Ä–∏—Å–æ–≤–∞—Ç—å –∫–∞—Ä—Ç–∏–Ω–∫—É –ø–æ –æ–ø–∏—Å–∞–Ω–∏—é, –ø—Ä–æ—Å—Ç–æ –æ—Ç–ø—Ä–∞–≤—å —Ç–µ–∫—Å—Ç–æ–≤–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ
  img2img: üé® –î–ª—è –∏–∑–º–µ–Ω–µ–Ω–∏—è –∫–∞—Ä—Ç–∏–Ω–∫–∏, –æ—Ç–ø—Ä–∞–≤—å –ø—Ä–∏–∫—Ä–µ–ø–ª–µ–Ω–Ω–æ–µ —Ñ–æ—Ç–æ —Å –æ–ø–∏—Å–∞–Ω–∏–µ–º
  rescale: üóø –û—Ç–ø—Ä–∞–≤—å —Ñ–æ—Ç–æ –æ—Ç–¥–µ–ª—å–Ω–æ, —á—Ç–æ–±—ã –ø–æ–≤—ã—Å–∏—Ç—å –µ–≥–æ –∫–∞—á–µ—Å—Ç–≤–æ –≤ 2 —Ä–∞–∑–∞ (–ø–æ–∫–∞ —á—Ç–æ –Ω–µ –¥–æ—Å—Ç—É–ø–Ω–æ)
  model: /artist - –í—ã–±–µ—Ä–∏ —Å–≤–æ–µ–≥–æ <b>–ò–ò - —Ö—É–¥–æ–∂–Ω–∏–∫–∞</b>, —É –Ω–∏—Ö –≤—Å–µ—Ö –µ—Å—Ç—å —Å–≤–æ–∏ –ø—Ä–µ–∏–º—É—â–µ—Å—Ç–≤–∞ –∏ –Ω–µ–¥–æ—Å—Ç–∞—Ç–∫–∏
  orientaiton: /picrute_orientation - –ò–∑–º–µ–Ω–µ–Ω–∏–µ –æ—Ä–∏–µ–Ω—Ç–∞—Ü–∏–∏ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è, –∑–∞—á–∞—Å—Ç—É—é –≤–ª–∏—è–µ—Ç –Ω–µ —Ç–æ–ª—å–∫–æ –Ω–∞ <b>—Ñ–æ—Ä–º—É –∫–∞—Ä—Ç–∏–Ω–∫–∏</b>, –Ω–æ –∏ –Ω–∞ –µ–µ <b>—Å–æ–¥–µ—Ä–∂–∞–Ω–∏–µ</b>
  retry: /retry - –ü–æ–≤—Ç–æ—Ä–∏—Ç—å —Å–≤–æ–π –ø–æ—Å–ª–µ–¥–Ω–∏–π –∑–∞–ø—Ä–æ—Å

warning:
  wait_or_cancel: ‚è≥ –ü–æ–∂–∞–ª—É–π—Å—Ç–∞ <b>–ø–æ–¥–æ–∂–¥–∏</b>, —Ç–≤–æ–π –∑–∞–ø—Ä–æ—Å –æ–±—Ä–∞–±–∞—Ç—ã–≤–∞–µ—Ç—Å—è.\n –ú–æ–∂–µ—à—å —Ç–∞–∫–∂–µ –æ—Ç–º–µ–Ω–∏—Ç—å –µ–≥–æ (/cancel)
  message_editing: –†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ —Å–æ–æ–±—â–µ–Ω–∏–π –Ω–µ –ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞–µ—Ç—Å—è üóø
  nothing_to_cancel: <i>–û—Ç–º–µ–Ω—è—Ç—å –Ω–µ—á–µ–≥–æ üòï</i>
  too_many_pictures: –°–ª–∏—à–∫–æ–º –º–Ω–æ–≥–æ –∫–∞—Ä—Ç–∏–Ω–æ–∫, –∏–∑–º–µ–Ω—è—é –ø–æ—Å–ª–µ–¥–Ω—é—é
  long_queue: –í –æ—á–µ—Ä–µ–¥–∏ –º–Ω–æ–≥–æ –∑–∞–ø—Ä–æ—Å–æ–≤, –ø—Ä–∏–¥–µ—Ç—Å—è –ø–æ—Ç–µ—Ä–ø–µ—Ç—å ‚è≥

error:
  bad_action: –ö —Å–æ–∂–∞–ª–µ–Ω–∏—é —ç—Ç–∞ —Ñ—É–Ω–∫—Ü–∏—è –ø–æ–∫–∞ —á—Ç–æ –Ω–µ –¥–æ—Å—Ç—É–ø–Ω–∞ üò≠
  whitelist: –û—à–∏–±–∫–∞. –¢–≤–æ–µ–≥–æ –Ω–∏–∫–Ω–µ–π–º–∞ –Ω–µ—Ç –≤ –º–æ–µ–º –±–µ–ª–æ–º —Å–ø–∏—Å–∫–µ. üíÄ
  bad_message: –¢–∞–∫–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ –Ω–µ –ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞–µ—Ç—Å—è üíÄ
  generation_error: –û—à–∏–±–∫–∞ –ø—Ä–∏ –æ–±—Ä–∞–±–æ—Ç–∫–µ —Å–æ–æ–±—â–µ–Ω–∏—è üíÄ
  unhandled_error: –ù–µ–∏–∑–≤–µ—Å–Ω–∞—è –æ—à–∏–±–∫–∞ üíÄ

