txt2img:
  name: ĞšĞ°Ñ€Ñ‚Ğ¸Ğ½ĞºĞ° Ğ¿Ğ¾ Ğ¾Ğ¿Ğ¸ÑĞ°Ğ½Ğ¸Ñ
  welcome_message: ğŸ‘©ğŸ¼â€ğŸ“ Hi, I'm <b>General Assistant</b>. How can I help you?

img2img:
  name: ĞŸÑ€ĞµĞ¾Ğ±Ñ€Ğ°Ğ·Ğ¾Ğ²Ğ°Ğ½Ğ¸Ğµ ĞºĞ°Ñ€Ñ‚Ğ¸Ğ½ĞºĞ¸ Ğ¿Ğ¾ Ğ¾Ğ¿Ğ¸ÑĞ°Ğ½Ğ¸Ñ
  welcome_message: ğŸ‘©ğŸ¼â€ğŸ’» Hi, I'm <b>Code Assistant</b>. How can I help you?

rescale:
  name: Ğ£Ğ²ĞµĞ»Ğ¸Ñ‡Ğ¸Ñ‚ÑŒ ĞºĞ°Ñ€Ñ‚Ğ¸Ğ½ĞºÑƒ Ğ² 2 Ñ€Ğ°Ğ·Ğ°
  welcome_message: ğŸ“ Hi, I'm <b>Text Improver</b>. Send me any text â€“ I'll improve it and correct all the mistakes
